package pl.krakow.nordic.szarki;

import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;

public class MainActivity extends AppCompatActivity {

    private SharedPreferences sp;
    private SharedPreferences.Editor de;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        pWordInitU1();
        aWordInitU1();

        pWordInitU2();
        aWordInitU2();

        pWordInitU3();
        aWordInitU3();

        pWordInitU4();
        aWordInitU4();

        pWordInitU5();
        aWordInitU5();

        pWordInitU6();
        aWordInitU6();

        pWordInitU7();
        aWordInitU7();



    }

    private void aWordInitU7() {
        sp = getSharedPreferences("aWordsU7", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT SEVEN WORD LIST - ENGLISH */

        de.putString("1", "auditor");
        de.putString("2", "forensic");
        de.putString("3", "convict (v)");
        de.putString("4", "litigation");
        de.putString("5", "bribery");
        de.putString("6", "manner");
        de.putString("7", "pivotal");
        de.putString("8", "notorious");
        de.putString("9", "evasion");
        de.putString("10","emerge (v)");
        de.putString("11","conceal (v)");
        de.putString("12","reveal (v)");
        de.putString("13","trail");
        de.putString("14","receipt");
        de.putString("15","gross");
        de.putString("16","asset");
        de.putString("17","liability");
        de.putString("18","payroll");
        de.putString("19","extraordinary");
        de.putString("20","discourage (v)");
        de.putString("21","encourage (v)");
        de.putString("22","invaluable");
        de.putString("23","spreadsheet");
        de.putString("24","compel (v)");
        de.putString("25","permit (v)");
        de.putString("26","prohibit (v)");
        de.putString("27","whilst");
        de.putString("28","arise from something (v)");
        de.putString("29","brought about by something");
        de.putString("30","due to");
        de.putString("31","originate (v)");
        de.putString("32","refrigerated");
        de.putString("33","recap (v)");
        de.putString("34","fortnightly");
        de.putString("35","executive");
        de.putString("36","appoint (v)");
        de.putString("37","reject (v)");
        de.putString("38","assure (v)");
        de.putString("39","chase something up (v)");
        de.putString("40","evaluate (v)");
        de.putString("41","breakdown");
        de.putString("42","petty cash");
        de.putString("43","comprehensive");
        de.putString("44","forefront");
        de.putString("45","fraudster");
        de.putString("46","makeover");
        de.putString("47","net worth");
        de.putString("48","policy-maker");
        de.putString("49","protection racket");
        de.putString("50","scam");
        de.putString("51","tax evasion");
        de.putString("52","undercover");
        de.putString("53","white-collar crime");
        de.putString("54","depreciation");
        de.putString("55","pellet");
        de.putString("56","snapshot");
        de.putString("57","knock-on");
        de.putString("58","misery");
        de.putString("59","notably");
        de.putString("60","raw materials");
        de.putString("61","stem from (v)");
        de.putString("62","in good shape");
        de.putString("63","iron out (v)");
        de.putString("64","starving");
        de.putString("65","take stock (v)");
        de.putString("66","tweak (v)");
        de.putString("67","open-plan office");
        de.putString("68","partition");
        de.putString("69","venue");
        de.putString("70","bodyshop");
        de.putString("71","chasing letter");
        de.putString("72","dent");
        de.putString("73","embezzle (v)");
        de.putString("74","evasive");
        de.putString("75","reprimand");
        de.putString("76","scratch");
        de.putString("77","sickie");
        de.putString("78","suspension");

        de.apply();
    }

    private void pWordInitU7() {
        sp = getSharedPreferences("pWordsU7", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT SEVEN WORD LIST - POLISH */

        de.putString("1", "rewident księgowy");
        de.putString("2", "sądowy");
        de.putString("3", "skazać");
        de.putString("4", "spór sądowy / proces");
        de.putString("5", "łapówka");
        de.putString("6", "sposób / maniera");
        de.putString("7", "kluczowy");
        de.putString("8", "znany / notoryczny");
        de.putString("9", "wykręt");
        de.putString("10","wyłaniać się");
        de.putString("11","ukrywać");
        de.putString("12","wyjawić / ujawnić");
        de.putString("13","ślad");
        de.putString("14","paragon");
        de.putString("15","brutto");
        de.putString("16","atut / zaleta");
        de.putString("17","odpowiedzialność / zobowiązanie");
        de.putString("18","lista płac");
        de.putString("19","niezwykły");
        de.putString("20","zniechęcać");
        de.putString("21","zachęcać");
        de.putString("22","nieceniony");
        de.putString("23","arkusz kalkulacyjny");
        de.putString("24","zmuszać");
        de.putString("25","pozwalać");
        de.putString("26","zabraniać");
        de.putString("27","podczas gdy");
        de.putString("28","mieć źródło w czymś");
        de.putString("29","spowodowany przez coś");
        de.putString("30","dzięki komuś / czemuś");
        de.putString("31","zapoczątkować / wymyślić");
        de.putString("32","ochłodzony");
        de.putString("33","streszczać / podsumowywać");
        de.putString("34","dwutygodniowy");
        de.putString("35","wykonawczy");
        de.putString("36","mianować");
        de.putString("37","odrzucać");
        de.putString("38","zapewniać");
        de.putString("39","przypomieć coś");
        de.putString("40","oceniać");
        de.putString("41","rozpad");
        de.putString("42","kasa podręczna");
        de.putString("43","wyczerpujący / obszerny");
        de.putString("44","ważna pozycja");
        de.putString("45","oszust");
        de.putString("46","przeróbka");
        de.putString("47","wartość netto");
        de.putString("48","ustawodawca");
        de.putString("49","wymuszenie haraczy");
        de.putString("50","oszustwo");
        de.putString("51","unikanie podatków");
        de.putString("52","tajniak");
        de.putString("53","przestępstwo rachunkowe");
        de.putString("54","tracenie na wartości");
        de.putString("55","pigułka");
        de.putString("56","szybki opis");
        de.putString("57","pośredni efekt");
        de.putString("58","nieszczęście");
        de.putString("59","szczególnie");
        de.putString("60","surowce");
        de.putString("61","wynikać z");
        de.putString("62","w dobrej formie");
        de.putString("63","usunąc przeszkody");
        de.putString("64","głodny");
        de.putString("65","oszacować coś");
        de.putString("66","usprawiedliwić");
        de.putString("67","otwarte biuro");
        de.putString("68","przegroda");
        de.putString("69","miejsce spotkania");
        de.putString("70","warsztat");
        de.putString("71","upomnienie do zapłaty");
        de.putString("72","wgniecenie");
        de.putString("73","zdefraudować");
        de.putString("74","wykrętny");
        de.putString("75","upomnienie");
        de.putString("76","zadraśnięcie");
        de.putString("77","wymówka");
        de.putString("78","zawieszenie");

        de.apply();

    }

    private void aWordInitU6() {
        sp = getSharedPreferences("aWordsU6", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT SIX WORD LIST - ENGLISH */

        de.putString("1", "ingredients");
        de.putString("2", "turnover");
        de.putString("3", "blockbuster");
        de.putString("4", "luxury");
        de.putString("5", "minority");
        de.putString("6", "entrepreneur");
        de.putString("7", "fragrance");
        de.putString("8", "knack");
        de.putString("9", "acquire (v)");
        de.putString("10","freed");
        de.putString("11","bank loan");
        de.putString("12","equity");
        de.putString("13","grant (v)");
        de.putString("14","leasing");
        de.putString("15","overdraft");
        de.putString("16","self-funding");
        de.putString("17","maintenance");
        de.putString("18","outright");
        de.putString("19","turn somebody down (v)");
        de.putString("20","come up (v)");
        de.putString("21","put forward (v)");
        de.putString("22","work out (v)");
        de.putString("23","check out (v)");
        de.putString("24","go through (v)");
        de.putString("25","due diligence");
        de.putString("26","draw up (v)");
        de.putString("27","set out (v)");
        de.putString("28","get through");
        de.putString("29","apparent");
        de.putString("30","forecast");
        de.putString("31","assumption");
        de.putString("32","awareness");
        de.putString("33","schedule");
        de.putString("34","assure (v)");
        de.putString("35","precise");
        de.putString("36","subsequent");
        de.putString("37","sufficient");
        de.putString("38","sophisticated");
        de.putString("39","predictive");
        de.putString("40","reinforce");
        de.putString("41","quibble (v)");
        de.putString("42","acknowledged");
        de.putString("43","unbeatable");
        de.putString("44","capable");
        de.putString("45","ethnic");
        de.putString("46","bandwagon");
        de.putString("47","batch");
        de.putString("48","emulate (v)");
        de.putString("49","found (v)");
        de.putString("50","nurture (v)");
        de.putString("51","outlet");
        de.putString("52","ring up (v)");
        de.putString("53","rub shoulders with");
        de.putString("54","sing somebody's praises");
        de.putString("55","stake");
        de.putString("56","yearn");
        de.putString("57","asset");
        de.putString("58","household");
        de.putString("59","outstanding");
        de.putString("60","pitch");
        de.putString("61","raw materials");
        de.putString("62","stain on");
        de.putString("63","temping agency");
        de.putString("64","track record");
        de.putString("65","weed out (v)");
        de.putString("66","black tie");
        de.putString("67","fancy dress");
        de.putString("68","plant");
        de.putString("69","sustainable");
        de.putString("70","awkward");
        de.putString("71","bluff");
        de.putString("72","do your homework");
        de.putString("73","field (v)");
        de.putString("74","nod (v)");
        de.putString("75","recap (v)");
        de.putString("76","threat");
        de.putString("77","elevator pitch");
        de.putString("78","faux pas");
        de.putString("79","high-end");
        de.putString("80","showcase");
        de.putString("81","snappy");
        de.putString("82","turnaround");
        de.putString("83","be up for (v)");
        de.putString("84","boost morale");
        de.putString("85","cunning");
        de.putString("86","drop someone a line (v)");
        de.putString("87","grab (v)");
        de.putString("88","hype (v)");
        de.putString("89","resilient");
        de.putString("90","think laterally (v)");
        de.putString("91","upbeat");

        de.apply();
    }

    private void pWordInitU6() {
        sp = getSharedPreferences("pWordsU6", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT SIX WORD LIST - POLISH */

        de.putString("1", "składniki");
        de.putString("2", "obrót");
        de.putString("3", "hit / przebój");
        de.putString("4", "luksury");
        de.putString("5", "mniejszość");
        de.putString("6", "przedsiębiorca");
        de.putString("7", "zapach / woń");
        de.putString("8", "wprawa / talent");
        de.putString("9", "nabyć / zdobyć");
        de.putString("10","swobodny");
        de.putString("11","pożyczka bankowa");
        de.putString("12","udział np. w kapitale");
        de.putString("13","udzielać / wyrażać zgodę");
        de.putString("14","dzierżawa");
        de.putString("15","przekroczenie stanu konta");
        de.putString("16","samofinansowanie");
        de.putString("17","utrzymanie");
        de.putString("18","pełnoprawy / niekwestionowany");
        de.putString("19","odrzucić kogoś");
        de.putString("20","zbliżyć się / pojawić się");
        de.putString("21","proponować coś / przedstawiać coś");
        de.putString("22","sprawdzać się / rozwiązać problem");
        de.putString("23","sprawdzać np. informacje");
        de.putString("24","przejść / przetrwać");
        de.putString("25","należyta staranność");
        de.putString("26","sporządzić / rozrysować");
        de.putString("27","postanowić / rozpocząć");
        de.putString("28","przedostać się / dodzwonić się");
        de.putString("29","oczywisty / widoczny");
        de.putString("30","prognoza / przewidywanie");
        de.putString("31","założenie / przypuszczenie");
        de.putString("32","świadomość / wiedza");
        de.putString("33","harmonogram");
        de.putString("34","zapewniać");
        de.putString("35","precyzyjny");
        de.putString("36","kolejny / późniejszy");
        de.putString("37","wystarczający");
        de.putString("38","wyrafinowany");
        de.putString("39","proroczy");
        de.putString("40","popierać / umacniać");
        de.putString("41","kłócić się o coś nieistotnego");
        de.putString("42","uznany");
        de.putString("43","bezkonkurencyjny");
        de.putString("44","kompetentny / sprawny");
        de.putString("45","etniczny");
        de.putString("46","idea lub rzecz która szybko staje się popularna");
        de.putString("47","porcja");
        de.putString("48","naśladować");
        de.putString("49","założyć partie, organizacje");
        de.putString("50","pomagać się komuś rozwijać");
        de.putString("51","sklep z markowymi rzeczami");
        de.putString("52","stracić lub zyskać określoną sume pieniędzy");
        de.putString("53","spotkać i rozmawiać z kimś znanym i bogatym");
        de.putString("54","chwalić kogoś przed innymi");
        de.putString("55","udział w jakimś biznesie");
        de.putString("56","pragnąć czegoś mocno");
        de.putString("57","kapitał / majątek");
        de.putString("58","gospodarstwo domowe");
        de.putString("59","niedokończony");
        de.putString("60","gadka z siłą perswazji");
        de.putString("61","surowe materiały / surowce");
        de.putString("62","presja spowodowana trudną sytuacją");
        de.putString("63","agencja pośrednictwa");
        de.putString("64","udokumentowana reputacja, osiągnięcia");
        de.putString("65","wyplenić coś / usunąć coś");
        de.putString("66","bardzo eleganckie męskie ciuchy");
        de.putString("67","przebranie za słabną osobę");
        de.putString("68","fabryka / przemysł");
        de.putString("69","zrównoważony / ekologiczny");
        de.putString("70","niezręczny");
        de.putString("71","blef");
        de.putString("72","wyciągać wnioski");
        de.putString("73","radzić sobie z czymś ciężkim");
        de.putString("74","kiwać głową");
        de.putString("75","podsumować");
        de.putString("76","zagrożenie");
        de.putString("77","krótkie podsumowanie biznesu");
        de.putString("78","nietakt");
        de.putString("79","produkt z najwyższej półki");
        de.putString("80","prezentacja czegoś w dobrym świetle");
        de.putString("81","krótki / przyciągający");
        de.putString("82","czas realizacji");
        de.putString("83","chcieć coś zrobić");
        de.putString("84","podnieść morale");
        de.putString("85","przebiegły");
        de.putString("86","skontaktować się z kimś");
        de.putString("87","przyciągnąć i zainteresować");
        de.putString("88","promować coś mocno");
        de.putString("89","szybko wyzdrowieć");
        de.putString("90","myśleć kreatywnie i nieszablonowo");
        de.putString("91","optymistyczny");

        de.apply();

    }

    private void aWordInitU5() {
        sp = getSharedPreferences("aWordsU5", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT FIVE WORD LIST - ENGLISH */

        de.putString("1","bundle");
        de.putString("2","dodgy");
        de.putString("3","double-edged sword");
        de.putString("4","endorse (v)");
        de.putString("5","gripe (v)");
        de.putString("6","inclined to believe");
        de.putString("7","on the house");
        de.putString("8","stack up");
        de.putString("9","suck");
        de.putString("10","thrive");
        de.putString("11","vertical market");
        de.putString("12","ongoing");
        de.putString("13","trickery");
        de.putString("14","deception");
        de.putString("15","dirupted");
        de.putString("16","blend (v)");
        de.putString("17","spare");
        de.putString("18","stealth");
        de.putString("19","subliminal");
        de.putString("20","timeshare");
        de.putString("21","coherency");
        de.putString("22","decline");
        de.putString("23","niche");
        de.putString("24","conduct (v)");
        de.putString("25","diversify (v)");
        de.putString("26","saturated market");
        de.putString("27","coupon");
        de.putString("28","marmelade");
        de.putString("29","razor");
        de.putString("30","maintain (v)");
        de.putString("31","postpone (v)");
        de.putString("32","compensation");
        de.putString("33","obstacle");
        de.putString("34","merit");
        de.putString("35","insurance");
        de.putString("36","merger");
        de.putString("37","takeover");
        de.putString("38","cold calling");
        de.putString("39","luncheon voucher");
        de.putString("40","on the clock");
        de.putString("41","tax-deductible");
        de.putString("42","comromise");
        de.putString("43","briefing");
        de.putString("44","credentials");
        de.putString("45","CRM");
        de.putString("46","grab someone's attetion");
        de.putString("47","handling");
        de.putString("48","trawl through (v)");
        de.putString("49","USP unique selling point");
        de.putString("50","courier");
        de.putString("51","flat");
        de.putString("52","fleet");
        de.putString("53","handset");
        de.putString("54","keep up with (v)");

        de.apply();
    }

    private void pWordInitU5() {
        sp = getSharedPreferences("pWordsU5", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT FIVE WORD LIST - POLISH */

        de.putString("1","sprzedaż wiązana / zestaw");
        de.putString("2","chytry /sprytny");
        de.putString("3","coś co ma pozytywne i negatywne aspekty");
        de.putString("4","zaakceptować");
        de.putString("5","narzekać");
        de.putString("6","skłonny uwierzyć");
        de.putString("7","na koszt firmy");
        de.putString("8","w porównaniu (against)");
        de.putString("9","bardzo złe / denerwujące");
        de.putString("10","dobrze prosperować");
        de.putString("11","rynek o wąskim zakresie produktu");
        de.putString("12","trwający");
        de.putString("13","oszustwo");
        de.putString("14","oszustwo / podstęp");
        de.putString("15","odwołany / zdeorganizowany");
        de.putString("16","mieszać");
        de.putString("17","zapasowy");
        de.putString("18","podstęp");
        de.putString("19","coś czego trzeba się domyśleć");
        de.putString("20","mieszkanie lub dom używany za opłatą czasowo");
        de.putString("21","spójność");
        de.putString("22","zanik / ubytek / strata");
        de.putString("23","nisza / wnęka");
        de.putString("24","przeprowadzać / przewodzić");
        de.putString("25","urozmaicać / różnicować");
        de.putString("26","rynek nasycony");
        de.putString("27","kupon");
        de.putString("28","marmolada");
        de.putString("29","żyletka");
        de.putString("30","podtrzymywać / utrzymywać / twierdzić");
        de.putString("31","odkładać");
        de.putString("32","rekompensata / odszkodowanie");
        de.putString("33","przeszkoda");
        de.putString("34","wartość / zasługa");
        de.putString("35","ubezpieczenie");
        de.putString("36","połączenie / fuzja");
        de.putString("37","przejęcie");
        de.putString("38","telefon od reklamodawcy");
        de.putString("39","bon na lunch");
        de.putString("40","na liczniku np. w samochodzie");
        de.putString("41","odpisanie od podatku");
        de.putString("42","kompromis");
        de.putString("43","instruktaż");
        de.putString("44","kwalifikacje");
        de.putString("45","zarządzanie relacjami z klientami");
        de.putString("46","przyciągnąć czyjąś uwagę");
        de.putString("47","prowadzenie");
        de.putString("48","wyszukać w dużym zbiorze danych");
        de.putString("49","coś co wyróżnia produkt");
        de.putString("50","kurier");
        de.putString("51","rozładowany");
        de.putString("52","zorganizowana grupa / flota");
        de.putString("53","słuchawka do telefonu");
        de.putString("54","być na bieżąco");

        de.apply();
    }

    private void aWordInitU4() {
        sp = getSharedPreferences("aWordsU4", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT FOUR WORD LIST - ENGLISH */

        de.putString("1","milestone");
        de.putString("2","due to");
        de.putString("3","purchase");
        de.putString("4","feasibility");
        de.putString("5","survey");
        de.putString("6","excavacation");
        de.putString("7","resettlement");
        de.putString("8","retreat");
        de.putString("9","touchy-feely");
        de.putString("10","blindfold");
        de.putString("11","crayon");
        de.putString("12","sincere");
        de.putString("13","merge (v)");
        de.putString("14","bunch");
        de.putString("15","shortcoming");
        de.putString("16","superior");
        de.putString("17","endure (v)");
        de.putString("18","impose (v)");
        de.putString("19","prevail (v)");
        de.putString("20","accomplish (v)");
        de.putString("21","aspiring");
        de.putString("22","buy into sth (v)");
        de.putString("23","offend (v)");
        de.putString("24","scope");
        de.putString("25","start from scratch (v)");
        de.putString("26","allied with");
        de.putString("27","apathy");
        de.putString("28","bang on");
        de.putString("29","be better off (v)");
        de.putString("30","dam");
        de.putString("31","foundation");
        de.putString("32","silly");
        de.putString("33","bully");
        de.putString("34","leader");
        de.putString("35","maverick");
        de.putString("36","workaholic");
        de.putString("37","anxious");
        de.putString("38","decisive");
        de.putString("39","over-critical");
        de.putString("40","single-minded");
        de.putString("41","unpredictable");
        de.putString("42","burn out (v)");
        de.putString("43","settle in (v)");
        de.putString("44","pull together (v)");
        de.putString("45","pass the buck (v)");
        de.putString("46","gets on well with (v)");
        de.putString("47","let somebody down (v)");
        de.putString("48","pull your weight (v)");
        de.putString("49","take it easy (v)");
        de.putString("50","appraisal interview");
        de.putString("51","hectic");
        de.putString("52","loner");
        de.putString("53","power plant");
        de.putString("54","inland");
        de.putString("55","accountant");
        de.putString("56","downshift");
        de.putString("57","pace of life");
        de.putString("58","evacuate");
        de.putString("59","generator");
        de.putString("60","impact (v)");
        de.putString("61","reactor");
        de.putString("62","seismic");
        de.putString("63","turn sth down (v)");
        de.putString("64","delight");
        de.putString("65","supervise (v)");
        de.putString("66","praise");
        de.putString("67","elicit (v)");
        de.putString("68","mess sth up (v)");
        de.putString("69","overdo (v)");
        de.putString("70","approach (v)");
        de.putString("71","foster (v)");
        de.putString("72","moreover");
        de.putString("73","therefore");
        de.putString("74","to sum up");
        de.putString("75","engage (v)");
        de.putString("76","touch on (v)");
        de.putString("77","accustomed");
        de.putString("78","deserted");
        de.putString("79","forecourt");
        de.putString("80","crucial");
        de.putString("81","could do with sth (v)");
        de.putString("82","dealer");
        de.putString("83","handle someone with kid gloves (v)");
        de.putString("84","mess");
        de.putString("85","put up with (v)");
        de.putString("86","sort out (v)");
        de.putString("87","top sth up (v)");
        de.putString("88","windscreen");
        de.putString("89","work your fingers to the bone (v)");

        de.apply();
    }

    private void pWordInitU4() {
        sp = getSharedPreferences("pWordsU4", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT FOUR WORD LIST - POLISH */

        de.putString("1","kamień milowy / ważny punkt");
        de.putString("2","w skutek");
        de.putString("3","zakup");
        de.putString("4","wykonalność");
        de.putString("5","ankieta / sondaż");
        de.putString("6","wykopalisko");
        de.putString("7","przesiedlenie");
        de.putString("8","odwrót");
        de.putString("9","wylewny / emocjonalny");
        de.putString("10","po omacku");
        de.putString("11","kredka");
        de.putString("12","szczery");
        de.putString("13","łączyć / scalać");
        de.putString("14","grupa");
        de.putString("15","niedociągnięcie");
        de.putString("16","lepszy");
        de.putString("17","znieść / wytrwać");
        de.putString("18","narzucać / dyktować");
        de.putString("19","panować / dominować");
        de.putString("20","ukończyć / wykonać");
        de.putString("21","ambitny");
        de.putString("22","dać się przekonać do czegoś");
        de.putString("23","obrazić kogoś");
        de.putString("24","zakres / możliwość");
        de.putString("25","zaczynać od początku");
        de.putString("26","sprzymierzony z / powiązany z");
        de.putString("27","obojętność");
        de.putString("28","dokładnie tak / zgadza się");
        de.putString("29","być w lepszej sytuacji");
        de.putString("30","tama / zapora");
        de.putString("31","fundamenty");
        de.putString("32","głupi / niemądry");
        de.putString("33","łobuz / oprych");
        de.putString("34","przywódca / lider");
        de.putString("35","indywidualista");
        de.putString("36","pracoholik");
        de.putString("37","zaniepokojony");
        de.putString("38","decydujący");
        de.putString("39","zbyt krytyczny");
        de.putString("40","zdeterminowany / mający jeden cel");
        de.putString("41","nieobliczalny");
        de.putString("42","wypalić się");
        de.putString("43","zaadoptować się");
        de.putString("44","współpracować");
        de.putString("45","przerzucić na kogoś odpowiedzialność");
        de.putString("46","być w dobrych stosunkach z");
        de.putString("47","zawieść kogoś");
        de.putString("48","dzielić z kimś prace");
        de.putString("49","uspokoić się");
        de.putString("50","rozmowa oceniająca");
        de.putString("51","nerwowy / napięty");
        de.putString("52","samotnik");
        de.putString("53","elektrownia");
        de.putString("54","śródlądowy");
        de.putString("55","księgowy");
        de.putString("56","zwolnienie tempa życia / mniej pieniędzy, więcej zadowolenia");
        de.putString("57","tempo życia");
        de.putString("58","ewakuacja");
        de.putString("59","agregator");
        de.putString("60","wpływać / mieć wpływ");
        de.putString("61","reaktor");
        de.putString("62","sejsmiczny");
        de.putString("63","odrzucić coś");
        de.putString("64","zachwyt");
        de.putString("65","nadzorować");
        de.putString("66","pochwała");
        de.putString("67","uzyskać");
        de.putString("68","zrujnować coś");
        de.putString("69","przesadzać");
        de.putString("70","zbliżać się / podchodzić");
        de.putString("71","pielęgnować / wspierać");
        de.putString("72","co więcej");
        de.putString("73","dlatego / zatem");
        de.putString("74","podsumowując");
        de.putString("75","angażować");
        de.putString("76","wspomieć o");
        de.putString("77","przyzwyczajony");
        de.putString("78","opustoszały");
        de.putString("79","plac / parking");
        de.putString("80","kluczowy");
        de.putString("81","chcieć czegoś");
        de.putString("82","handlarz");
        de.putString("83","obchodzić się z kimś ze szczególną ostrożnością");
        de.putString("84","bałagan");
        de.putString("85","wytrzymywać / tolerować");
        de.putString("86","uporządkować / rozwiązać problem");
        de.putString("87","dopełnić coś");
        de.putString("88","przednia szyba");
        de.putString("89","zaharować się / ciężko pracować");

        de.apply();
    }

    private void aWordInitU3() {
        sp = getSharedPreferences("aWordsU3", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT THREE WORD LIST - ENGLISH */

        de.putString("1","design");
        de.putString("2","durability");
        de.putString("3","environmental friendliness");
        de.putString("4","modernity");
        de.putString("5","price");
        de.putString("6","quality");
        de.putString("7","value for money");
        de.putString("8","reliability");
        de.putString("9","superficial");
        de.putString("10","sake");
        de.putString("11","household");
        de.putString("12","obsolescence");
        de.putString("13","executive");
        de.putString("14","remain (v)");
        de.putString("15","elusive");
        de.putString("16","craze");
        de.putString("17","flaw");
        de.putString("18","shrink (v)");
        de.putString("19","burst (v)");
        de.putString("20","struggle (v)");
        de.putString("21","intrinsically");
        de.putString("22","appreciate (v)");
        de.putString("23","roughly");
        de.putString("24","schedule");
        de.putString("25","renown");
        de.putString("26","lean (v)");
        de.putString("27","entrepreneurial");
        de.putString("28","admission");
        de.putString("29","commitment");
        de.putString("30","folk");
        de.putString("31","cease (v)");
        de.putString("32","readily");
        de.putString("33","sour");
        de.putString("34","appeal");
        de.putString("35","marvel (v)");
        de.putString("36","amid");
        de.putString("37","rumble (v)");
        de.putString("38","rattling");
        de.putString("39","fake");
        de.putString("40","planned / build-in obsolence");
        de.putString("41","take for granted (v)");
        de.putString("42","beholder");
        de.putString("43","stakeholder");
        de.putString("44","workmanship");
        de.putString("45","shoddy");
        de.putString("46","flimsy");
        de.putString("47","intend");
        de.putString("48","deluxe");
        de.putString("49","heavy-duty");
        de.putString("50","disposable");
        de.putString("51","cost-effective");
        de.putString("52","fit for purpose");
        de.putString("53","fragile");
        de.putString("54","reliable");
        de.putString("55","tough");
        de.putString("56","compulsory");
        de.putString("57","warehouse");
        de.putString("58","mislay (v)");
        de.putString("59","slightly");
        de.putString("60","mend (v)");
        de.putString("61","fade (v)");
        de.putString("62","heap");
        de.putString("63","night shift");
        de.putString("64","round-the-clock");
        de.putString("65","skip (v)");
        de.putString("66","stack");
        de.putString("67","take the blame");
        de.putString("68","stock");
        de.putString("69","visual aids");
        de.putString("70","jargon");
        de.putString("71","inappropriate");
        de.putString("72","acronym");
        de.putString("73","signposting");
        de.putString("74","digress (v)");
        de.putString("75","make or break");
        de.putString("76","transit");
        de.putString("77","lab-ware");
        de.putString("78","batch");
        de.putString("79","penalty");
        de.putString("80","leak");
        de.putString("81","stain");
        de.putString("82","assure (v)");
        de.putString("83","nuisance");
        de.putString("84","dashboard");
        de.putString("85","straw");
        de.putString("86","pallet");
        de.putString("87","teething problems");
        de.putString("88","vial");
        de.putString("89","forklift");
        de.putString("90","bin liner");
        de.putString("91","fibre");
        de.putString("92","shelf life");
        de.putString("93","newlyweds");
        de.putString("94","shed");
        de.putString("95","bulk");
        de.putString("96","wastage");
        de.putString("97","scratch");
        de.putString("98","tray");
        de.putString("99","punnet");
        de.putString("100","decay (v)");
        de.putString("101","shrivel (v)");
        de.putString("102","bruise");
        de.putString("103","harvest");
        de.putString("104","incentive");
        de.putString("105","shallow");
        de.putString("106","squash (v)");
        de.putString("107","ripe");
        de.putString("108","sound");
        de.putString("109","fad");
        de.putString("110","rattle");
        de.putString("111","stream");
        de.putString("112","trap");
        de.putString("113","white goods");
        de.putString("114","exacting");
        de.putString("115","machine (v)");
        de.putString("116","admit (v)");
        de.putString("117","underlying");
        de.putString("118","loading bay");
        de.putString("119","tactful");
        de.putString("120","overflow");
        de.putString("121","rack");
        de.putString("122","spot");

        de.apply();
    }

    private void pWordInitU3() {
        sp = getSharedPreferences("pWordsU3", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT THREE WORD LIST - POLISH */

        de.putString("1","projekt");
        de.putString("2","trwałość");
        de.putString("3","przyjazny dla środowiska");
        de.putString("4","nowoczesność");
        de.putString("5","koszt / cena");
        de.putString("6","jakość");
        de.putString("7","wartość pieniądza");
        de.putString("8","niezawodność");
        de.putString("9","powierzchowny");
        de.putString("10","wzgląd");
        de.putString("11","gospodarstwo domowe");
        de.putString("12","starzenie się / zanikanie");
        de.putString("13","wykonawczy");
        de.putString("14","pozostawać / trwać");
        de.putString("15","nieuchwytny / trudny do zdefiniowania");
        de.putString("16","szał");
        de.putString("17","wada");
        de.putString("18","kurczyć / zanikać");
        de.putString("19","rozerwać / eksplodować");
        de.putString("20","borykać się");
        de.putString("21","wewnętrznie");
        de.putString("22","doceniać");
        de.putString("23","w przybliżeniu / brutalnie / szorstko / prymitywnie");
        de.putString("24","rozkład / harmonogram");
        de.putString("25","rozgłos / renoma");
        de.putString("26","opierać się / oprzeć");
        de.putString("27","przedsiębiorczy");
        de.putString("28","wstęp / przyznanie się");
        de.putString("29","zaangażowanie");
        de.putString("30","ludowy");
        de.putString("31","zaprzestać");
        de.putString("32","łatwo / ochoczo");
        de.putString("33","kwaśny");
        de.putString("34","apel / wezwanie");
        de.putString("35","podziwiać");
        de.putString("36","wśród / między");
        de.putString("37","grzmieć / huczeć / dudnić");
        de.putString("38","porywisty / energiczny");
        de.putString("39","imitacja / podróbka");
        de.putString("40","???");
        de.putString("41","uważać za rzecz oczywistą");
        de.putString("42","obserwator");
        de.putString("43","interesariusz");
        de.putString("44","jakość wykonania");
        de.putString("45","tandetny");
        de.putString("46","lichy / nietrwały");
        de.putString("47","intencja");
        de.putString("48","luksusowy");
        de.putString("49","przemysłowy / trwały");
        de.putString("50","jednorazowy");
        de.putString("51","opłacalny");
        de.putString("52","nadający się do celu");
        de.putString("53","kruchy");
        de.putString("54","niezawodny");
        de.putString("55","twardy");
        de.putString("56","obowiązkowy");
        de.putString("57","magazyn");
        de.putString("58","gubić");
        de.putString("59","nieco / nieznacznie");
        de.putString("60","zaszyć");
        de.putString("61","blaknąć / zgasnąć");
        de.putString("62","sterta / stos");
        de.putString("63","nocna zmiana");
        de.putString("64","całą dobę");
        de.putString("65","pominąć");
        de.putString("66","stos");
        de.putString("67","wziąć winę");
        de.putString("68","zapas");
        de.putString("69","pomoce wizualne");
        de.putString("70","żargon");
        de.putString("71","niewłaściwy");
        de.putString("72","akronim");
        de.putString("73","podpowiadanie");
        de.putString("74","błądzić / snuć dywagacje");
        de.putString("75","rozstrzygający");
        de.putString("76","przejazd");
        de.putString("77","sprzęt laboratoryjny");
        de.putString("78","partia / seria");
        de.putString("79","kara");
        de.putString("80","nieszczelność / przeciek");
        de.putString("81","plama");
        de.putString("82","zapewnić / zabezpieczyć");
        de.putString("83","kłopot / utrapienie");
        de.putString("84","deska rozdzielcza");
        de.putString("85","słoma");
        de.putString("86","paleta");
        de.putString("87","początkowe problemy");
        de.putString("88","fiolka");
        de.putString("89","wózek widłowy");
        de.putString("90","worek na śmieci");
        de.putString("91","błonnik");
        de.putString("92","okres ważności");
        de.putString("93","nowożeńcy");
        de.putString("94","buda / szopa / szałas");
        de.putString("95","ogrom / wielka ilość");
        de.putString("96","ubytek / strata");
        de.putString("97","zadraśnięcie");
        de.putString("98","miska / tacka");
        de.putString("99","koszyczek");
        de.putString("100","rozkładać / gnić");
        de.putString("101","uschnąć / pokurczyć się");
        de.putString("102","siniak");
        de.putString("103","żniwa");
        de.putString("104","zachęta / bodziec");
        de.putString("105","płytki / niski");
        de.putString("106","zgniatać / miażdżyć");
        de.putString("107","dojrzały");
        de.putString("108","zdrowy");
        de.putString("109","chwilowa moda");
        de.putString("110","grzechotka / kołatka");
        de.putString("111","strumień");
        de.putString("112","pułapka");
        de.putString("113","AGD");
        de.putString("114","wymagający");
        de.putString("115","obrabiać");
        de.putString("116","przyznać");
        de.putString("117","podstawowy / leżący u podstaw");
        de.putString("118","strefa załadunku");
        de.putString("119","taktowny");
        de.putString("120","przepełnienie");
        de.putString("121","stojak");
        de.putString("122","miejsce / punkt");

        de.apply();
    }

    private void aWordInitU2() {
        sp = getSharedPreferences("aWordsU2", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT TWO WORD LIST - ENGLISH */

        de.putString("1","upgrade (v)");
        de.putString("2","crash (v)");
        de.putString("3","went down (v)");
        de.putString("4","fell down (v)");
        de.putString("5","set up (v)");
        de.putString("6","keep in the loop (v)");
        de.putString("7","give a ring (v)");
        de.putString("8","fill in (v)");
        de.putString("9","keep in touch (v)");
        de.putString("10","profitable");
        de.putString("11","trivial");
        de.putString("12","small talk");
        de.putString("13","mustn't grumble");
        de.putString("14","alleviate (v)");
        de.putString("15","fine");
        de.putString("16","forethought");
        de.putString("17","forthwith");
        de.putString("18","officialese");
        de.putString("19","time frame");
        de.putString("20","prospects");
        de.putString("21","salary");
        de.putString("22","increase (v)");
        de.putString("23","overtime");
        de.putString("24","down time");
        de.putString("25","drag someone kicking and screaming (v)");
        de.putString("26","malicious");
        de.putString("27","outsource");
        de.putString("28","recruit");
        de.putString("29","subsidiary");
        de.putString("30","turnover");
        de.putString("31","boost (v)");
        de.putString("32","waste (v)");
        de.putString("33","plug-in");
        de.putString("34","wonder (v)");
        de.putString("35","issue");
        de.putString("36","regularly");
        de.putString("37","cram");
        de.putString("38","mess up (v)");
        de.putString("39","oddly");
        de.putString("40","overhaul (v)");
        de.putString("41","pressure cooker");
        de.putString("42","slick");
        de.putString("43","take a breather (v)");
        de.putString("44","margin");
        de.putString("45","stretched");
        de.putString("46","patch");
        de.putString("47","bug");
        de.putString("48","bulky");
        de.putString("49","carbon footprint");
        de.putString("50","difficulty");
        de.putString("51","immediately");
        de.putString("52","solve (v)");
        de.putString("53","we realize");
        de.putString("54","recognized");
        de.putString("55","alleviating");
        de.putString("56","adjacent to");
        de.putString("57","imperative");
        de.putString("58","inadequate");
        de.putString("59","overall");
        de.putString("60","mad dash (v)");
        de.putString("61","boardroom");
        de.putString("62","labour");
        de.putString("63","headcount");
        de.putString("64","fierce");
        de.putString("65","efficiency");
        de.putString("66","irrelevant");
        de.putString("67","occur (v)");
        de.putString("68","polish up (v)");
        de.putString("69","better off");
        de.putString("70","bury (v)");
        de.putString("71","cope(with) (v)");
        de.putString("72","errand");
        de.putString("73","untold");
        de.putString("74","asap");
        de.putString("75","give someone a hand (v)");
        de.putString("76","hassle (v)");
        de.putString("77","in the know");
        de.putString("78","in the loop");
        de.putString("79","snail mail");
        de.putString("80","acquaintance");
        de.putString("81","solicit");
        de.putString("82","unambiguous");

        de.apply();
    }

    private void pWordInitU2() {
        sp = getSharedPreferences("pWordsU2", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT TWO WORD LIST - POLISH */

        de.putString("1","zaktualizować");
        de.putString("2","psuć się");
        de.putString("3","zepsuć się");
        de.putString("4","upaść");
        de.putString("5","ustawić / zainstalować");
        de.putString("6","informować na bieżąco");
        de.putString("7","zadzwonić");
        de.putString("8","dopasować");
        de.putString("9","być w kontakcie");
        de.putString("10","opłacalny");
        de.putString("11","banalny");
        de.putString("12","pogawędka");
        de.putString("13","nie można narzekać");
        de.putString("14","łagodzić");
        de.putString("15","grzywna / mandat");
        de.putString("16","przezorność");
        de.putString("17","bezzwłocznie");
        de.putString("18","urzędnik");
        de.putString("19","ramy czasowe");
        de.putString("20","horyzont / perspektywa");
        de.putString("21","wynagrodzenie");
        de.putString("22","zwiększać");
        de.putString("23","po godzinach");
        de.putString("24","okres przestoju");
        de.putString("25","zmusić kogoś");
        de.putString("26","złośliwy");
        de.putString("27","korzystanie z usług innej firmy");
        de.putString("28","rekrut");
        de.putString("29","pomocniczy");
        de.putString("30","obrót handlowy");
        de.putString("31","zwiększyć / podnosić");
        de.putString("32","marnować");
        de.putString("33","wtyczka / podłączać");
        de.putString("34","zastanawiać się");
        de.putString("35","problem");
        de.putString("36","regularnie");
        de.putString("37","dopchać");
        de.putString("38","namieszać / robić bałagan");
        de.putString("39","dziwnie");
        de.putString("40","zbadać dokładnie / wyremontować");
        de.putString("41","szybkowar");
        de.putString("42","zręczny");
        de.putString("43","wziąć oddech");
        de.putString("44","marża");
        de.putString("45","rozciągnięte");
        de.putString("46","łata (poprawka lub uaktualnienie do programu)");
        de.putString("47","infekcja wirusowa");
        de.putString("48","obszerny / masywny");
        de.putString("49","ślad węglowy");
        de.putString("50","trudność");
        de.putString("51","natychmiast");
        de.putString("52","rozwiązać");
        de.putString("53","zdajemy sobie sprawę");
        de.putString("54","rozpoznawalne / uznane");
        de.putString("55","łagodzenie");
        de.putString("56","w sąsiedztwie");
        de.putString("57","rozkazujący");
        de.putString("58","niewystarczający");
        de.putString("59","ogólny / całkowity");
        de.putString("60","szybko coś zrobić");
        de.putString("61","sala konferencyjna");
        de.putString("62","siła robocza");
        de.putString("63","liczba zatrudnień");
        de.putString("64","mający dużo siły lub energii");
        de.putString("65","efektywność");
        de.putString("66","niemający związku");
        de.putString("67","zdarzać się / występować");
        de.putString("68","szlifować");
        de.putString("69","lepsze połorzenie");
        de.putString("70","pogrzebać");
        de.putString("71","radzić sobie z");
        de.putString("72","zlecenie");
        de.putString("73","nieopisany / niemierzalny");
        de.putString("74","as soon as possible / jak szybko się da");
        de.putString("75","pomóc komuś");
        de.putString("76","przeszkadzać");
        de.putString("77","dobrze poinformowany / w kręgu zaufanych");
        de.putString("78","w kręgu poinformowanych decydentów");
        de.putString("79","śmieciowa wiadomość");
        de.putString("80","znajomy");
        de.putString("81","prosić o wsparcie");
        de.putString("82","jednoznaczny");

        de.apply();
    }

    private void aWordInitU1() {
        sp = getSharedPreferences("aWordsU1", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT ONE WORD LIST - ENGLISH */
        de.putString("1","beverage");
        de.putString("2","divident");
        de.putString("3","equity/equities");
        de.putString("4","utility");
        de.putString("5","bear market");
        de.putString("6","bond");
        de.putString("7","bull market");
        de.putString("8","euphoric");
        de.putString("9","staple");
        de.putString("10","trough");
        de.putString("11","cost of good sold");
        de.putString("12","fixed cost");
        de.putString("13","operating profit");
        de.putString("14","plot");
        de.putString("15","royality");
        de.putString("16","sales revenue");
        de.putString("17","variable cost");
        de.putString("18","wholesaler");
        de.putString("19","achieve");
        de.putString("20","budget");
        de.putString("21","deal with sth (v)");
        de.putString("22","handle (v)");
        de.putString("23","liaise (v)");
        de.putString("24","objective");
        de.putString("25","reference");
        de.putString("26","set up (v)");
        de.putString("27","arrange (v)");
        de.putString("28","check");
        de.putString("29","ensure (v)");
        de.putString("30","establish (v)");
        de.putString("31","follow (v)");
        de.putString("32","increase (v)");
        de.putString("33","introduce (v)");
        de.putString("34","monitor (v)");
        de.putString("35","plan (v)");
        de.putString("36","research");
        de.putString("37","update (v)");
        de.putString("38","cap (v)");
        de.putString("39","earnings");
        de.putString("40","exacerbate (v)");
        de.putString("41","extracurricular");
        de.putString("42","faculty");
        de.putString("43","fee");
        de.putString("44","hike");
        de.putString("45","placement");
        de.putString("46","spark (v)");
        de.putString("47","subsidy");
        de.putString("48","employability");
        de.putString("49","tuition");
        de.putString("50","hesitate (v)");
        de.putString("51","borrow (v)");
        de.putString("52","obtain (v)");
        de.putString("53","subsidize (v)");
        de.putString("54","boost (v)");
        de.putString("55","deep pockets");
        de.putString("56","drop out (v)");
        de.putString("57","enhance (v)");
        de.putString("58","miss out (v)");
        de.putString("59","start over (v)");
        de.putString("60","working party");
        de.putString("61","exceed (v)");
        de.putString("62","chair (v)");
        de.putString("63","draw up (v)");
        de.putString("64","manage (v)");
        de.putString("65","be dimissed (v)");
        de.putString("66","be laid off (v)");
        de.putString("67","be made redundant (v)");
        de.putString("68","be on assignment (v)");
        de.putString("69","be promoted (v)");
        de.putString("70","be resting (v)");
        de.putString("71","be suspended (v)");
        de.putString("72","be transferred (v)");
        de.putString("73","give in notice (v)");
        de.putString("74","join a company (v)");
        de.putString("75","quit (v)");
        de.putString("76","take a sabbatical (v)");
        de.putString("77","harass (v)");
        de.putString("78","measure (v)");
        de.putString("79","debt");
        de.putString("80","mining");
        de.putString("81","real estate");
        de.putString("82","retail");
        de.putString("83","share");
        de.putString("84","breakeven");
        de.putString("85","peak");
        de.putString("86","plunge (v)");
        de.putString("87","turnover");
        de.putString("88","resources");
        de.putString("89","trend");
        de.putString("90","bind (v)");
        de.putString("91","lay off (v)");
        de.putString("92","throughly");
        de.putString("93","come along (v)");
        de.putString("94","downsize (v)");
        de.putString("95","fancy");
        de.putString("96","put on weight (v)");
        de.putString("97","streamline (v)");
        de.putString("98","tutoring");
        de.putString("99","benchmark");
        de.putString("100","feedback");
        de.putString("101","personality clash");
        de.putString("102","accomplishment");
        de.putString("103","bartending");
        de.putString("104","brokering");
        de.putString("105","debating society");
        de.putString("106","embark on (v)");
        de.putString("107","outgoing");
        de.putString("108","tender");
        de.putString("109","venue");
        de.putString("110","heritage");
        de.putString("111","procurement");
        de.putString("112","sit back (v)");
        de.putString("113","tailor (v)");

        de.apply();
    }

    private void pWordInitU1() {
        sp = getSharedPreferences("pWordsU1", MODE_PRIVATE);
        de = sp.edit();

        /* UNIT ONE WORD LIST - POLISH */
        de.putString("1","picie");
        de.putString("2","dywidenta /jakiś zysk");
        de.putString("3","udział/y");
        de.putString("4","udogodnienie");
        de.putString("5","rynek zniżkujący");
        de.putString("6","obligacja");
        de.putString("7","rynek zwyżkujący");
        de.putString("8","euforyczny");
        de.putString("9","surowiec");
        de.putString("10","rynna /czas kiedy coś wzrasta i upada regularnie");
        de.putString("11","koszt sprzedanych towarów");
        de.putString("12","koszt stały");
        de.putString("13","zysk z działalności operacyjnej");
        de.putString("14","działka /posiadana ziemia");
        de.putString("15","królewski");
        de.putString("16","przychody ze sprzedaży");
        de.putString("17","koszt zmienny");
        de.putString("18","hurtownik");
        de.putString("19","osiągać");
        de.putString("20","budżet");
        de.putString("21","radzić sobie z czymś");
        de.putString("22","obchodzić się / zająć się");
        de.putString("23","działać w porozumieniu");
        de.putString("24","cel");
        de.putString("25","odniesienie / wzmianka / kompetencje");
        de.putString("26","ustawić coś");
        de.putString("27","zorganizować");
        de.putString("28","czek");
        de.putString("29","zapewnić");
        de.putString("30","ustawiać / ustanawiać");
        de.putString("31","śledzić");
        de.putString("32","zwiększać");
        de.putString("33","wprowadzić");
        de.putString("34","kontrolować");
        de.putString("35","planować");
        de.putString("36","poszukiwanie");
        de.putString("37","aktualizować");
        de.putString("38","ustalenie limitu");
        de.putString("39","zarobki");
        de.putString("40","pogorszyć");
        de.putString("41","zajęcia dodatkowe");
        de.putString("42","grono pedagogiczne");
        de.putString("43","honorarium");
        de.putString("44","nagły wzrost");
        de.putString("45","praktyki");
        de.putString("46","wzniecić coś");
        de.putString("47","dotacja");
        de.putString("48","zdolność do zatrudnienia");
        de.putString("49","czesne");
        de.putString("50","wahać się");
        de.putString("51","pożyczyć");
        de.putString("52","nabyć");
        de.putString("53","dotować");
        de.putString("54","zwiększać");
        de.putString("55","bogaci ludzie");
        de.putString("56","odpaść");
        de.putString("57","uwydatniać");
        de.putString("58","tracić / przegapić");
        de.putString("59","zacząć od nowa");
        de.putString("60","grupa robocza");
        de.putString("61","wykraczać");
        de.putString("62","przewodniczyć");
        de.putString("63","sporządzić");
        de.putString("64","poradzić sobie / gospodarować");
        de.putString("65","być odwołanym dyscyplinarnie");
        de.putString("66","być zwolnionym");
        de.putString("67","być niepotrzebnym");
        de.putString("68","być na zlecenie");
        de.putString("69","dostać awans");
        de.putString("70","odpoczywać");
        de.putString("71","być zawieszonym");
        de.putString("72","być przeniesionym");
        de.putString("73","złożyć wymówienie");
        de.putString("74","dołączyć do firmy");
        de.putString("75","porzucić");
        de.putString("76","wziać urlop naukowy");
        de.putString("77","prześladować / molestować / nękać");
        de.putString("78","zmierzyć");
        de.putString("79","posiadane pieniądze");
        de.putString("80","wydobycie np. węgla");
        de.putString("81","biznes nieruchomości");
        de.putString("82","sprzedaż detaliczna");
        de.putString("83","akcja / udział");
        de.putString("84","granica opłacalności");
        de.putString("85","szczyt");
        de.putString("86","popaść np. w długi");
        de.putString("87","obrót handlowy");
        de.putString("88","zasoby");
        de.putString("89","tendencja");
        de.putString("90","ograniczać się");
        de.putString("91","zwalniać z pracy");
        de.putString("92","całkowicie");
        de.putString("93","zbliżać się");
        de.putString("94","zmniejszyć rozmiar");
        de.putString("95","fantastyczny");
        de.putString("96","przytyć");
        de.putString("97","ulepszać np. organizacje");
        de.putString("98","nauczanie");
        de.putString("99","miara odniesienia / porównawcza");
        de.putString("100","sprzężenie zwrotne");
        de.putString("101","konflikt osobowości");
        de.putString("102","osiągnięcie");
        de.putString("103","praca za barem");
        de.putString("104","pośredniczenie");
        de.putString("105","grupa dyskusyjna");
        de.putString("106","zacząć np. projekt");
        de.putString("107","towarzyski");
        de.putString("108","oferta przetargowa");
        de.putString("109","miejsce spotkania");
        de.putString("110","dziedzictwo kulturowe");
        de.putString("111","zaopatrzenie");
        de.putString("112","zrelaksować się");
        de.putString("113","dostosować się");

        de.apply();
        //de.putString("","");

    }


    public void clickUnitOne(View view) {
        Intent intent = new Intent(MainActivity.this, UnitActivity.class);
        String unit = "U1";
        int count = 113;
        intent.putExtra("unit", unit);
        intent.putExtra("count", count);
        startActivity(intent);
    }

    public void clickUnitTwo(View view) {
        Intent intent = new Intent(MainActivity.this, UnitActivity.class);
        String unit = "U2";
        int count = 82;
        intent.putExtra("unit", unit);
        intent.putExtra("count", count);
        startActivity(intent);
    }

    public void clickUnitThree(View view) {
        Intent intent = new Intent(MainActivity.this, UnitActivity.class);
        String unit = "U3";
        int count = 122;
        intent.putExtra("unit", unit);
        intent.putExtra("count", count);
        startActivity(intent);
    }

    public void clickUnitFour(View view) {
        Intent intent = new Intent(MainActivity.this, UnitActivity.class);
        String unit = "U4";
        int count = 89;
        intent.putExtra("unit", unit);
        intent.putExtra("count", count);
        startActivity(intent);
    }

    public void clickUnitFive(View view) {
        Intent intent = new Intent(MainActivity.this, UnitActivity.class);
        String unit = "U5";
        int count = 54;
        intent.putExtra("unit", unit);
        intent.putExtra("count", count);
        startActivity(intent);
    }

    public void clickUnitSix(View view) {
        Intent intent = new Intent(MainActivity.this, UnitActivity.class);
        String unit = "U6";
        int count = 91;
        intent.putExtra("unit", unit);
        intent.putExtra("count", count);
        startActivity(intent);
    }

    public void clickUnitSeven(View view) {
        Intent intent = new Intent(MainActivity.this, UnitActivity.class);
        String unit = "U7";
        int count = 78;
        intent.putExtra("unit", unit);
        intent.putExtra("count", count);
        startActivity(intent);
    }

    public void cliclAll(View view) {
        Intent intent = new Intent(MainActivity.this, AllActivity.class);
        startActivity(intent);
    }
}
